name: Burp DAST Scan

# This workflow is triggered on every push to the main branch.
# You can change this to a different event, such as a pull_request,
# or a schedule.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs to run in this workflow.
jobs:
  # The job you provided, with a name for better readability in the GitHub UI.
  netspaker_scan_job:
    name: Run Burp DAST Scan
    runs-on: ubuntu-latest
    steps:
      # # Step 1: Checkout the repository code. This is a best practice for most workflows.
      # - name: Checkout Repository
      #   uses: actions/checkout@v3

      # # Step 2: The Netsparker Enterprise Scan job, as you provided.
      # # It uses the netsparker/Netsparker-Cloud-GitHub-Actions action.
      # # The 'id' is used to reference the outputs of this step later.
      # - name: Start Netsparker Enterprise Scan
      #   uses: netsparker/Netsparker-Cloud-GitHub-Actions@v1.0.1
      #   id: netsparker-enterprise-scan-step
      #   with:
      #     # The Website ID and Profile ID are hardcoded values from your provided YAML.
      #     website-id: 'df94791a-bf20-4951-5271-b32d003a99e7'
      #     scan-type: 'FullWithSelectedProfile'
      #     profile-id: '6f836de2-2bb7-4884-71ed-b3300357f10b'
      #     # Security credentials are passed using GitHub secrets.
      #     user-id: ${{ secrets.NETSPARKER_USER_ID }}
      #     api-token: ${{ secrets.NETSPARKER_API_TOKEN }}
      #     base-url: 'https://ie.invicti.com'
      #     # Controls whether the workflow fails based on scan results.
      #     fail-on-level: 'DoNotFail'
      #     # Set to 'false' to start the scan and continue the workflow without waiting for completion.
      #     wait-for-completion: false

      - name: Echo
        run: echo "Burp 2"
      # what is github workspace?
      - name: Run Burp scan
        run: |
          docker run --network host --rm \
            -u $(id -u) -v ${{ github.workspace }}:${{ github.workspace }}:rw -w ${{ github.workspace }} \
            -e BURP_ENTERPRISE_API_KEY=${{ secrets.BURP_API_KEY }} \
            -e BURP_ENTERPRISE_SERVER_URL=${{ secrets.BURP_URL }} \
            -e BURP_CONFIG_FILE_PATH=${{ github.workspace }}/.burp/burp-config.yml \
            -e BURP_REPORT_FILE_PATH=${{ github.workspace }}/burp_junit_report.xml \
            -e BURP_REPORT_FORMAT="JUNIT,BURP_XML" \
            public.ecr.aws/portswigger/enterprise-scan-container:latest
      # - name: Environment cleanup
      #   if: always()
      #   run: sh ${{ github.workspace }}/scripts/scan-cleanup.sh ${{ github.workspace }}

      # # Step 3: Display the message from the Netsparker action's output.
      # - name: Display Scan Request Message
      #   run: echo "${{ steps.netsparker-enterprise-scan-step.outputs.scan-message }}"