name: Build and test application

on:
  workflow_dispatch:

jobs:
  burp_scan:
    name: Run Burp Suite scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Run Burp scan
        run: |
          docker run --network host --rm \
            -u $(id -u) -v ${{ github.workspace }}:${{ github.workspace }}:rw -w ${{ github.workspace }} \
            -e BURP_ENTERPRISE_API_KEY=${{ secrets.BURP_API_KEY }} \
            -e BURP_ENTERPRISE_SERVER_URL=${{ secrets.BURP_URL }} \
            -e BURP_START_URL=${{ secrets.BURP_START_URL }}
      # - name: Environment cleanup
      #   if: always()
      #   run: sh ${{ github.workspace }}/scripts/scan-cleanup.sh ${{ github.workspace }}
      # - name: Upload JUnit report as artifact
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Upload Burp report
      #     path: ${{ github.workspace }}/burp_junit_report.xml
      # - name: Publish web app scan results to pipeline
      #   if: always()
      #   id: publish-burp-junit-test-report
      #   uses: mikepenz/action-junit-report@v3
      #   with:
      #     check_name: View Burp scan results
      #     report_paths: ${{ github.workspace }}/burp_junit_report.xml
      #     fail_on_failure: false
      #     require_tests: false
      # - name: Upload Burp XML
      #   id: upload-burp-results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: burp-results
      #     path: ${{ github.workspace }}/burp_xml_report.xml
  deploy:
    name: Deploy application
    needs: [burp_scan]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying..."